import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

/**
 * Badge Component Variants
 *
 * @purpose 
 * - Generates Tailwind CSS classes for badge styling.
 * - Supports multiple visual variants (`default`, `secondary`, `destructive`, `success`, `outline`).
 * - Handles focus, hover, and transition styles consistently.
 *
 * @param {object} options - Variant options for badge styling.
 * @param {"default" | "secondary" | "destructive" | "success" | "outline"} [options.variant] - Badge visual style. Defaults to "default".
 *
 * @returns {string} A string of Tailwind CSS classes for the badge component.
 * @throws None
 * @sideEffects None
 *
 * @example
 * const classes = badgeVariants({ variant: "success" });
 * <span className={classes}>Active</span>
 */
const badgeVariants = cva(
  "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
  {
    variants: {
      variant: {
        default:
          "border-transparent bg-primary text-primary-foreground hover:bg-primary/80",
        secondary:
          "border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80",
        destructive:
          "border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80",
        success:
          "border-transparent bg-success text-success-foreground hover:bg-success/80",
        outline: "text-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)


/**
 * Props for the Badge component.
 */
export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

/**
 * Badge component.
 *
 * @purpose 
 * - Renders a small label or status badge with different visual variants.
 * - Uses Tailwind CSS classes generated by `badgeVariants` for styling.
 * - Supports hover, focus, and transition effects.
 *
 * @param {BadgeProps} props - Props for the Badge component.
 * @param {"default" | "secondary" | "destructive" | "success" | "outline"} [props.variant] - Visual style variant. Defaults to "default".
 * @param {string} [props.className] - Optional additional CSS classes.
 * @param {...React.HTMLAttributes<HTMLDivElement>} props - Other div attributes.
 *
 * @returns {JSX.Element} A styled div representing the badge.
 * @throws None
 * @sideEffects None
 *
 * @example
 * <Badge variant="success">Active</Badge>
 * <Badge variant="destructive" className="text-sm">Failed</Badge>
 */
function Badge({ className, variant, ...props }: BadgeProps) {
  return (
    <div className={cn(badgeVariants({ variant }), className)} {...props} />
  )
}


/**
 * CSS class generator for Badge component variants.
 *
 * @purpose 
 * - Returns a string of Tailwind CSS classes for different badge styles.
 *
 * @param {object} options - Variant options for badge styling.
 * @param {"default" | "secondary" | "destructive" | "success" | "outline"} [options.variant] - Badge visual style.
 * @returns {string} Tailwind CSS classes string for the badge.
 * @throws None
 * @sideEffects None
 *
 * @example
 * const classes = badgeVariants({ variant: "success" });
 * <div className={classes}>Active</div>
 */
export { Badge, badgeVariants }
